services:
    queueGateway:
        class: Pheanstalk_Pheanstalk
        arguments:
            - 127.0.0.1
    queue:
        class: Opine\Queue\Service
        arguments:
            - %root%
            - "@queueGateway"
    worker:
        class: Opine\Queue\Worker
        arguments:
            - %root%
            - "@queueGateway"
            - "@topic"
